dist: xenial
sudo: false

language: scala

jdk:
  - openjdk11

scala:
  - 2.12.8

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage ^test

after_success: sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "l+a3jvflGsjEN1DBI873VRk0abEpRblUH8J/5P7mZFzCGC0dlhyfJQSFb1ij9QZwPszs9Or2XN8AqOvj0MXJPDc3GN9xU2CvzlqvCIQARxWn4RdzrwQhiO7Wm52jiOKy1kL3JlGfrWN7rPA9wAAeOJU3z3aru5jtFJ+sQKdqDDO2DAJtiMbq2Fukmtm9BpKtBhMufauiCkrY0DUbkf3WoxzdrEWQh9FK/RL5Ov4bodmMO86GX2TQ/9fsAVUnt0xMp0Qrw+1qcgQavuDa8Khrq1oaHg3H1AABA+5mYj2KgE0T7eYp/t6NgPAFVHD5TlvBJ6DFUG8V3/lYZya94dKUAeKsRwgEO7HrE85CIeraBhQOrMqBe/oo/7zsVX3v8U2y8cBfHmt8nrz4Aci5DPdrZw/nMze5ewVSnwwSc0D0VV72KtqNzmuPtydlk6GE9Oug6JHJF7l/R+tN1smCBT2dQ+Gr+cQaSs2mHvFS5m3XgzPVpZwox+agecwx6uuNPufAVsZLa8ExYLWXMfdkuAg/luee6iuv1cJLjmsAgEh873RmnYOqkDUmx9lp7W5md+l/ZwpYosx2gzGNnAK0SxBhTJ8cO9KlxdFtr7eC3NnmyDZ1rKpoZMTWA50ldG6UyOwotCqMVWfAFvzmI7lYv8O+Cda3xYJWYvzJzLF7DavihhI="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete